# Generated by Django 3.1.3 on 2020-12-02 17:27

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201202_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
