# Generated by Django 3.1.3 on 2020-12-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_search_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_furnished',
        ),
        migrations.AddField(
            model_name='listing',
            name='lounges',
            field=models.IntegerField(default=0, verbose_name='lounges'),
        ),
    ]
