# Generated by Django 3.1.3 on 2020-12-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20201204_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_furnished',
            field=models.BooleanField(default=False, verbose_name='is furnished'),
        ),
    ]
